FROM node:12.22.12 AS builder

RUN echo "deb http://archive.debian.org/debian buster main" > /etc/apt/sources.list && \
    echo "deb http://archive.debian.org/debian-security buster/updates main" >> /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y python make g++ && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build -- --prod

FROM nginx:1.19-alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist/kanban-ui /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d

EXPOSE 80
