#cd ~/doco/astn-dvps/kanban-frontend
#nano Dockerfile

# Используем Node.js для сборки Angular-приложения
FROM node:14 AS builder

WORKDIR /app

# Копируем package.json и package-lock.json и устанавливаем зависимости
COPY package*.json ./
RUN npm install

# Копируем остальные файлы и собираем Angular-приложение
COPY . .
RUN npm run build --prod

# Используем nginx для отдачи статических файлов
FROM nginx:alpine

# Копируем собранные файлы из предыдущего stage
COPY --from=builder /app/dist/kanban-ui /usr/share/nginx/html

# Копируем собственный nginx.conf
# COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
