version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: kanban-postgres
    environment:
      POSTGRES_DB: kanban
      POSTGRES_USER: kanban
      POSTGRES_PASSWORD: kanban
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kanban -d kanban"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - kanban-net

  backend:
    image: back:latest
    container_name: kanban-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kanban
      SPRING_DATASOURCE_USERNAME: kanban
      SPRING_DATASOURCE_PASSWORD: kanban
      SPRING_LIQUIBASE_CHANGE-LOG: classpath:/db/changelog/db.changelog-master.xml
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - kanban-net
    restart: unless-stopped

  frontend:
    image: front:latest
    container_name: kanban-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - kanban-net
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  kanban-net:
    driver: bridge
